coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 50%
ignore:
  - 'node_modules/**'
  - 'android/**'
  - 'ios/**'
  - 'cypress/**'
  - 'dist/**'
  - 'public/**'
  - 'resources/**'
  - 'coverage/**'
