name: Feature Request
description: Suggest a new feature
labels: [feature]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Provide a concise description of your proposal.
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this implemented?
